name: lilypad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-03-29
        components: clippy, rustfmt
    - name: Build and test
    - run: cargo fmt --check
    - run: cargo clippy --release
    - run: cargo build --release
    - run: cargo test --release
